### ISSUE TITLE
alter set_att_list in replication_set_table

### ISSUE THREAD

**Issue by patdenis** [2ndQuadrant/pglogical#102]
hi,
  there is any pglogical.function to alter set_att_list in replication_set_table?
i need to add column.
if i alter set_att_list "mannualy" the change don't take affect immidattly.
to replicate new column i must do alter_subscription_disable and alter_subscription_enable or truncate table.
thanks

**Comment by PJMODOS** [comment]
Depends, if you want to copy the existing data, then it indeed needs resynchronization (not necessary to truncate manually, usually alter_subscriber_resynchronize_table() takes care of it). If you don't want to copy the existing data then removing and re-adding the table in same transaction (with synchronize_data := false as option when adding the table) will work just fine. And the missing simple alter for now is intentional exactly because we don't have automatic resynchronization of missing data for the column so you as user need to think about what you are doing first.
