### ISSUE TITLE
How to drop tables on provider?

### ISSUE THREAD

**Issue by rusticnerd** [2ndQuadrant/pglogical#145]
I have a simple database that includes a partitioned table. On the provider node, when I try to remove a child via DROP TABLE, I get:

`ERROR:  invalid non-zero objectSubId for object class 2466511`

I thought that perhaps this happened because the table existed in the provider's replication set. After removing the child table using pglogical.replication_set_remove_table(), I get the same error.

On the provider node, the pglogical.tables still lists the child table. However, the 'set_name' column is empty. I'm not sure how to safely drop this child table.

On the subscriber node, I can remove the child table without issue.

**Comment by eulerto** [comment]
> ERROR: invalid non-zero objectSubId for object class 2466511

This message is from Postgres. It is part of the code that handles object dependencies. This object class number 2466511 brings my attention since the catalogs usually have numbers less than 16384.

> On the provider node, the pglogical.tables still lists the child table. However, the 'set_name' column is empty. I'm not sure how to safely drop this child table.

If `set_name` is empty, it means that table is not part of the replication set.

By this time, I believe you cannot provider additional details about this environment. If this is still an issue, please open a new issue including as much detail as possible (a self-contained test case would be a good start).
