### ISSUE TITLE
Drop extension pglogical do not drop schema

### ISSUE THREAD

**Issue by mpasquini** [2ndQuadrant/pglogical#189]
pglogical 2.2.0 PG 10.5
with no nodes nor subscribers running: 
```sql
drop extension pglogical
```
or
```sql
drop extension pglogical cascade
```
It not remove the schema 'pglogical'

**Comment by eulerto** [comment]
AFAICS this is **not** a pglogical issue. I would say that it is the way Postgres handles the extension. pglogical uses `schema = pglogical` in its `pglogical.control` file. Because of the `schema` option, Postgres automatically creates the `pglogical` schema (see `CreateExtensionInternal` -- `backend/commands/extension.c`). However, this schema cannot be added as an extension dependency (so it would be dropped too) because the extension is already a schema dependency. It would create a dependency loop.

Postgres should probably remove the schema that it created as part of the CREATE EXTENSION command. Since it doesn't, you should DROP SCHEMA as a workaround.
