### ISSUE TITLE
Feature Request: Print warning when the subscribed db(remote) is not same with current db.

### ISSUE THREAD

**Issue by derkan** [2ndQuadrant/pglogical#200]
When configuring subscriptions with `pglogical`, it will be good to RAISE a NOTICE/WARNING when local db name is not same as remote subscribed database in DSN.

**Comment by ringerc** [comment]
Why? The local and remote db names can differ, and routinely do. Our regression tests rely on it. What issue(s) do you encounter with this?

I know there are some potential issues relating to `COMMENT ON DATABASE ...`  and a few other commands where `pg_dump` encodes the upstream database name in the dump. If there is no upstream DB of the same name on the downstream DB, the restore can fail. The same is true for a `SECURITY LABEL` and maybe `GRANT`s IIRC.

Are you encountering an issue like that? If so, there's not much we can do about it. In theory we could maybe filter the ToC from `pg_restore` and transform the entries, but that's a very messy workaround. On PostgreSQL 11 those issues should go away because core has fixed the underlying problem; see [commit b3f8401205afdaf63cb20dc316d44644c933d5a1[(https://git.postgresql.org/gitweb/?p=postgresql.git;h=b3f8401205afdaf63cb20dc316d44644c933d5a1)

**Comment by derkan** [comment]
I faced problem in #37. Closing.
