### ISSUE TITLE
Incompatible API change between 2.2.2 and 2.3.0

### ISSUE THREAD

**Issue by robert-pang** [2ndQuadrant/pglogical#241]
We just tested upgrading our pglogical extension from 2.2.2 to 2.3.0 and notice an incompatible API change to `pglogical.create_subscription()` that changes the `synchronize_structure` parameter from boolean to text type and breaks our application. This API change is not called out in the release notes. Is this change intended? Or will there be a plan to revert and preserve compatibility?

https://github.com/2ndQuadrant/pglogical/blob/REL2_3_0/pglogical--2.2.2--2.3.0.sql#L3

**Comment by klando** [comment]
the  change is intended, there is no clear consensus at the moment of writing as to how to address this issue.

The original function is:

```
CREATE FUNCTION pglogical.create_subscription(
    subscription_name name, provider_dsn text
  , replication_sets text[] = '{default,default_insert_only,ddl_sql}'
  , synchronize_structure boolean = false
  , synchronize_data boolean = true
  , forward_origins text[] = '{all}', apply_delay interval DEFAULT '0')
```

Another function with same name, even with another parameter (assuming it has a DEFAULT) won't allow PostgreSQL to know what function to call. Suppose we just add a `synchronize_structure_objects text[] default '{none}'`, then when a user execute:

`SELECT pglogical.create_subscription('my_sub', 'my_dsn');` PostgreSQL won't know what to do.
Or we make the new parameter without a DEFAULT, but then what was the point of having default in the first place ?

**Comment by PJMODOS** [comment]
Yeah we can't have 2 definitions, that would confuse Postgres as well, so the current API is the new API.

It should have been highlighted in the release notes indeed.

**Comment by petere** [comment]
This has been fixed in version 2.3.1, which restores the old API.

**Comment by robert-pang** [comment]
Thank you very much for updating the API to make it backward compatible.

**Comment by brauchle** [comment]
@petere has this feature been removed completely or is there a plan to reintroduce the feature to only have the structure of the replicated tables synchronized? 

Could probably be done by adding another optional param instead of refactorring the existing one, f.e. only_sync_replicated_structure with a default =true to make it backwards compatible.

Imho this is would be a quite useful feature, for me _synchronize_structure_ is not usable because I only want to sync a handful of a few hundred tables within my database without having the whole structure of the provider on the subscriber...

**Comment by petere** [comment]
> @petere has this feature been removed completely or is there a plan to reintroduce the feature to only have the structure of the replicated tables synchronized?

both :)
