### ISSUE TITLE
How often is the sequence synchronized?

### ISSUE THREAD

**Issue by SuperChengWu** [2ndQuadrant/pglogical#247]
I saw this sentence in the document，I want to know how often the sequence is synchronized?Is it possible to set the synchronization interval?
`The state of sequences added to replication sets is replicated periodically and not in real-time. `

**Comment by eulerto** [comment]
Sequences are synchronized between MIN_SLEEP (5s) and MAX_SLEEP (180s), starting with 10s [1] i.e. [interval is variable](https://github.com/2ndQuadrant/pglogical/blob/REL2_x_STABLE/pglogical_manager.c#L220). If sequences are updated, interval is less by a factor of 2, otherwise, it is greater by a factor of 2. MIN_SLEEP, MAX_SLEEP, INITIAL_SLEEP are not configurable parameters; they are [hardcoded](https://github.com/2ndQuadrant/pglogical/blob/REL2_x_STABLE/pglogical_manager.c#L35).
