### ISSUE TITLE
2.3.1 remove useful functionalities

### ISSUE THREAD

**Issue by scaturigo** [2ndQuadrant/pglogical#278]
In the 2.3.1 version you have removed two useful functions :

Allow replicating tables and sequences to different names on the target node
Add option to only synchronize the structure of replicated relations

Why ? Do you plan to reintroduce them ?

**Comment by nataraj30** [comment]
Replicating to Different Schema and Tables were an more useful update in 2.3.0 version... Shall we expect these to be added in upcoming releases?

**Comment by nataraj30** [comment]
I am working on replicating data to different destination name table from source table using pglogical 2.3.0 with row filter, found that some rows are missing from subscriber table.
### Replication scenario:
pglogical version: 2.3.0, 2 pg instances(provider and subscriber): Postgresql 11.4.
table 't' is the replicating table in one pg instance and tables 't1', 't2' are the subscriber tables in another pg instance..
_Table definition for t, t1, t2:_
create table t(id int not null,created_at timestamp with time zone NOT NULL, id2 int not null, id3 int not null, name text, PRIMARY KEY( id, id2, id3));

**Replication sets:**
1)
select pglogical.create_replication_set('r1');
select pglogical.replication_set_add_table('r1','t', row_filter:='hashint4(id) >=-2147483648 and hashint4(id) <= -1 and hashint4(id2) >= 0 and hashint4(id2) <= 2147483647 and id3 >= 1 and id3 <= 200',reltarget:='t1');
2)
select pglogical.create_replication_set('r2');
select pglogical.replication_set_add_table('r2','t',row_filter:='hashint4(id) >= 0 and hashint4(id) <= 2147483647 and hashint4(id2) >=-2147483648 and hashint4(id2) <= -1 and id3 >= 201 and id3 <= 400', reltarget := 't2');

After creating 2 seperate subscriptions for r1 and r2, at the end of subscriptions... i found the data missing in subscriber table t1.
applying the replication row_filter of 'r1' over the table 't' gave _67712_ row counts, but the overall row count of table 't1' gave _61308_ row counts, exactly **6404** rows missed... 

the log of subscriber node has:
```

LOG:  starting apply for subscription s1
ERROR:  schema "" does not exist
CONTEXT:  apply INSERT in commit before 0/4A04AFE8, xid 1954458 committed at 2020-09-03 22:35:56.900533+05:30 (action #2) from node replorigin 1
LOG:  apply worker [30591] at slot 1 generation 163 exiting with error

```
I get this data miss problem while pgbench runs simultaneously and inserts data to replicating table. If there is no incoming queries on this whole replication process then this problem not occuring...

_I understood that there were some issues because of that you have removed this different schema thing and updated with older same schema approach in 2.3.2 version..._

**1. It would be nice if you provide any workaround to avoid this missing data, till you republish pglogical with different schema thing.
2. Different schema approach is very very much useful, Any plan to include this in upcoming release or when it will be available?**

**Comment by petere** [comment]
As the release notes said, the functionality caused issues for some users, so it was removed and it will be reintroduced in the future.
