### ISSUE TITLE
pg_logical/snapshots dir huge

### ISSUE THREAD

**Issue by jingjingan** [2ndQuadrant/pglogical#297]
Hi，
I have postgresql9.6 on different servers; they are similar.
But  one server has huge pg_logical/snapshots dir, the content of the dir does not clean automaticly.
All other servers has same config, but others servers can auto clean  pg_logical/snapshots dir - only keep the last 3 minutes data.

Please see the snapshot of "correct servers":
![image](https://user-images.githubusercontent.com/43785771/103080626-2c816d00-4611-11eb-8896-4615d853ae02.png)

the snapshot of "huge pg_logical/snapshots server":

![image](https://user-images.githubusercontent.com/43785771/103080681-4d49c280-4611-11eb-9b47-d7c9467cf14f.png)

All replication works fine.
Similar issue happens to pg_xlog, other servers auto clean but only one server keeps all data.

And I found that pglogical keep sending tcp packages to subscription DBs, but there is no DB change.
Could you help check?

**Comment by yannikrust** [comment]
@jingjingan Have you solved this issue? If yes could you share your solution? I ran into the same problem.

**Comment by jingjingan** [comment]
@yannikrust Yes, I had resolved this issue. You can check this link: https://github.com/zalando/patroni/issues/205 
My issue was "There are some "staled" replication slots on replica." and followed the instructions in that link could solve it.

Hope this helps!

**Comment by DEvil0000** [comment]
I face the same issue with pgsql 12.12 and pglogical 2.3.2.
I checked the replication slots and they are busy getting back in sync/catching up.
Is it possible that the files do not get cleaned while pglogical is busy catching up?
Or was this possibly fixed in a later version of pglogical?

edit:
as soon as your partition is filled to the brim the replication slots of course go to some not replicating state..
Is it possible that it will try to fetch all data first and apply it at once instead of in chunks (in catchup)?
Looks like I can not recover from this easily - any hints?
