### ISSUE TITLE
Error when calling pg_logical_slot_peek_changes

### ISSUE THREAD

**Issue by gudmundurp** [2ndQuadrant/pglogical#319]
When I execute the following query:
 
 `SELECT` * FROM pg_logical_slot_peek_changes('name', NULL, NULL, 'include-timestamp', 'on', 'startup_params_format', '1', 'max_proto_version', '1', 'min_proto_version', `'1');`

I get the following error:
`ERROR:`  logical decoding output plugin "pglogical_output" produces binary output, but function "pg_logical_slot_peek_changes(name,pg_lsn,integer,text[])" expects textual data`

Does anyone know what I am doing wrong here?

I am using pglogical version 2.3.3

**Comment by eulerto** [comment]
pglogical uses 2 protocol formats: `json` and `native` (default). The former uses the `textual` and the later `binary`. Since you don't specify a `proto_format` parameter, it is using `native` that supports `binary`. Hence, you should use `pg_logical_slot_peek_binary_changes` instead of `pg_logical_slot_peek_changes`.

You should probably want to use a human-friendly bytea output so

```
SET bytea_output TO escape;
```

It seems you forgot to inform the replication set using `pglogical.replication_set_names` parameter.

There is no such `include-timestamp` parameter. You are probably mixing output plugins. This is a wal2json parameter.

**Comment by gudmundurp** [comment]
I managed to get this working with:

SELECT * FROM pg_logical_slot_peek_changes('name', NULL, NULL, 'include-timestamp', 'on', 'startup_params_format', '1', 'max_proto_version', '1', 'min_proto_version', '1', 'proto_format', 'json');

Thank you.
