### ISSUE TITLE
After drop pglogical. It didn't drop event trigger

### ISSUE THREAD

**Issue by alantang888** [2ndQuadrant/pglogical#370]
Hello, I dropped pglogical after migration. But when we drop a view on public schema. I still got `permission denied for schema pglogical` error. After some search. Look like pglogical created event trigger to make pglogical can work. But drop pglogical didn't clean those event trigger.

By the way. May I know which event trigger is created? 

Using psql 12.7 on Aurora.

**Comment by eulerto** [comment]
pglogical does not use event triggers since 2.0.0. (Unless you create an event trigger such as [automatic assignment of replication sets for new tables](https://github.com/2ndQuadrant/pglogical/blob/REL2_x_STABLE/docs/README.md#automatic-assignment-of-replication-sets-for-new-tables)). What's your pglogical version? How did you drop the pglogical extension?

**Comment by alantang888** [comment]
I don't remember. That was come with AWS Aurora (just ran `create extension pglogical`). I didn't check the actual running version at that moment (AWS docs mention should 2.x). I remember I just ran `drop extension pglogical` to drop pglogical. And those DB is not admin by me now. Can't get more info.
So maybe close this issue?

**Comment by eulerto** [comment]
Another possibility is that AWS uses a modified version.
