### ISSUE TITLE
pglogical sync delay

### ISSUE THREAD

**Issue by venkatabn** [2ndQuadrant/pglogical#39]
Hi,

We are currently exploring pglogical tool. Firstly, we do find pglogical a great tool which can be used to replicate tables. We are currently recommending one of our customers to evaluate this tool as a replacement for Slony to avoid various complexities.

Whist i am still new to this tool, I have the following queries -

Query 1 :

When i set up pglogical replication between PostgreSQL instance - 9.5 and 9.4, the replication works fine, but, there seems to be a delay in replicating the data changes. Not sure why and how to figure out. I am not sure if i am missing something here ? The setup is very simple with two postgresql instances running on the same host. Any help would be appreciated here.

Query 2:

pglogical can only be used to replicate tables with primary keys ?

Regards,
Venkata B N

Fujitsu Australia

**Comment by ringerc** [comment]
Hi. Sorry, I thought I replied to this earlier but I don't see a reply in the history here. This is really intended as a bug tracker, rather than a Q&A forum. General questions are better posted to pglogical-list@2ndquadrant.com or via the web UI at https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list .

In brief, it's hard to answer (1) without logs and details, so lets take that to the forum/mailing list. Information like how long the delay is, whether it always happens, whether each row seems delayed or it's bursts, etc would be good. As well, of course, as the exact pglogical version.

For (2), per the documentation, you can replicate tables without primary keys, but only for INSERTs. Otherwise you must have a primary key.

I'll close this ticket; please follow up on the forum/mailing list.
