### ISSUE TITLE
Upgrading Pglogical

### ISSUE THREAD

**Issue by asr1901** [2ndQuadrant/pglogical#49]
We are currently running:

postgresql94-pglogical-output-1.1.0-1_2ndQuadrant.el6.x86_64
pglogical-rhel-1.0-2.noarch
postgresql94-pglogical-1.1.2-1_2ndQuadrant.el6.x86_64

We would like to use the new row filtering that seems to be available in the latest version.  Do we only need to run the "1.20->1.3.0.sql" file?  Or do we need to reinstall the new RPM's and redo all of our subscriptions, etc? essentially re-install on every db.

Also, we are running postgresql-9.4

**Comment by ringerc** [comment]
You must install the new RPMs, since there are code changes. The extension script for pglogical is just the "glue" between the C code of the extension and the rest of PostgreSQL. If you try to run it in isolation you'll just get a mess.

To upgrade to a new release version you:

* install the new RPMs
* `ALTER EXTENSION pglogical UPDATE;`

However, row filtering isn't in 1.2.0, it's only in the 1.3 development series. There hasn't been a pglogical 1.3 release yet, so you can't just install new RPMs unless you build them yourself. You'll need to wait until the 1.3.0 release is tagged and the RPMs are built.

If you want to try it now you can, but be warned that when there are later updates to the development series you will probably have to manually apply the changes to the extension scripts. I do not recommend doing so on a production database.

If you want to try it on a dev/test environment you can:

* `git clone` the pglogical tree
* `git checkout master`
* Compile pglogical from source code
* Stop PostgreSQL
* Uninstall the pglogical RPMs
* `make install` to install the new pglogical
* Start PostgreSQL
* `ALTER EXTENSION pglogical UPDATE;`

**Comment by ringerc** [comment]
Since this isn't a bug or feature request I'm closing this ticket. Please follow up on the mailing list / forum at https://groups.google.com/a/2ndquadrant.com/forum/#!forum/bdr-list or by mailing pglogical-list@2ndquadrant.com .

**Comment by asr1901** [comment]
Thank you for the response, I'll use the mailing list next time.
