### ISSUE TITLE
2nd quadrant APT key expired

### ISSUE THREAD

**Issue by camilleldn** [2ndQuadrant/pglogical#82]
http://packages.2ndquadrant.com/pglogical/apt/AA7A6805.asc expired a handful of hours ago (March 23, 2017 at 12:44 AM), so we're not able to install pglogical on ubuntu/debian at the moment. 

Is there an up-to-date key we can use?

**Comment by ringerc** [comment]
We've pushed a new key for BDR.

I'll do the same for pglogical shortly.

**Comment by ringerc** [comment]
On 23 March 2017 at 18:25, Craig Ringer <craig@2ndquadrant.com> wrote:
> We've pushed a new key for BDR.
>
> I'll do the same for pglogical shortly.

You can apt-key import the BDR key file in the mean time, or gpg
--recv-key it, since it's the same key ID.

-- 
 Craig Ringer                   http://www.2ndQuadrant.com/
 PostgreSQL Development, 24x7 Support, Training & Services

**Comment by camilleldn** [comment]
@ringerc just downloaded`AA7A6805.asc`. perfect, thank you so much for your help!

**Comment by ringerc** [comment]
Thanks.

I've updated the key in the pglogical repo too now.

There's no way around users needing to re-import it though.

**Comment by inoutglobal** [comment]
Hi, iam tying to update the key, but it is expired.

pub   2048R/AA7A6805 2015-03-24 [expired: 2019-03-23]
