### ISSUE TITLE
Document procedure for updating pglogical

### ISSUE THREAD

**Issue by chad-iris** [2ndQuadrant/pglogical#85]
I could not find any instructions for updating pglogical to a new release.  Perhaps there is some general/tribal knowledge about updated extensions that applies, but for those of us not used to updating extensions on operational systems knowing the correction procedure (restart required?, re-definition of subscriptions, etc.? hot-patch possible?) would be very valuable.

Ideally some instructions would go or be linked from here:
https://www.2ndquadrant.com/en/resources/pglogical/pglogical-installation-instructions/

Hopefully I haven't missed something obvious.  Thanks for the great pglogical work!

**Comment by jfinzel** [comment]
Basically, the extension is updated like any other postgres extension: you install the new packages on the target server and run `ALTER EXTENSION UPDATE`, but it does require a restart to actually load the updated C code because it uses shared_preload_libraries: https://www.postgresql.org/docs/9.5/static/sql-alterextension.html

**Comment by chad-iris** [comment]
OK, those a just the details we need.  I humbly recommend that it's worth a small section in the docs for pglogical.
thanks!

**Comment by PJMODOS** [comment]
Agreed, we'll add that section.
